### ISSUE TITLE
提示浏览器版本过低

### ISSUE THREAD

**Issue by thunderiser** [sduspeaksoftware/QiangGuo_Banishment_StudyStrenthenCountryTool#3]
如题，我用的是win10 LTSC 2019，所有补丁都是最新的，IE11和Chrome都是最新的，但仍然提示版本过低

**Comment by rayiooo** [comment]
所有设备都会在主页面提示版本过低，但一般不影响使用，可以自动运行下去。如果无法正常运行，请先使用windows虚拟机，待之后移植到C#上就不会有这个问题了。
