### ISSUE TITLE
3.1版本腾讯云装上无法运行，本地电脑上不能更新到3.2

### ISSUE THREAD

**Issue by jiangjunxia** [sduspeaksoftware/QiangGuo_Banishment_StudyStrenthenCountryTool#6]
3.1版本腾讯云装上无法运行，本地电脑上可以运行，但刷不了分，更新到3.2失败

**Comment by licett** [comment]
同问，3.2更新失败，关闭后管理员运行也失败

**Comment by rayiooo** [comment]
环境为.net framework 4.6.1以及vc++14支持库，检查环境是否支持，3.1版本安装时有提醒。
更新失败问题，查看软件内公告板，按照3.2.3版本进行手动更新。

**Comment by rayiooo** [comment]
更新失败问题大多是权限不够，以管理员身份运行程序，或者将软件剪切到C盘以外的盘可解决。
